variables:
  - name: number
    value: 10

stages:
  - stage: demo
    jobs:
      - job: setVariable
        displayName: Set Variable
        steps:
          - script: |
              echo ${ { variables.number } }
              echo $(number)
            displayName: First variable pass
          - bash: echo "##vso[task.setvariable variable=number]20"
            displayName: Set new variable value
          - script: |
              echo ${ { variables.number } }
              echo $(number)
            displayName: Second variable pass
      - job: createFile
        displayName: Create File
        dependsOn: Set Variable
        steps:
          - script: |
              touch file.txt
              for i in {1..$(number)};do echo "Welcome $i times" >> file.txt;done
              cat file.txt
