parameters:
  - name: image
    displayName: Pool Image
    value: "windows-latest"

variables:
  - name: one
    value: initialValue
  - name: two
    value: initialValue

stages:
  - stage: demo
    jobs:
      - job: build
        displayName: build
        steps:
          - script: |
              echo ${ { variables.one  }  }
              echo $(one)
            displayName: First variable pass
          - bash: echo "##vso[task.setvariable variable=one]secondValue"
            displayName: Set new variable value
          - script: |
              echo ${ { variables.one } }
              echo $(one)
            displayName: Second variable pass

      - job: test_variables
        displayName: Test Variables
        dependsOn: build
        steps:
          - script: |
              echo "Testing Parameters:"
              echo "Image parameter value: ${{ parameters.image }}"
            displayName: Test Parameters
          - script: |
              echo "Testing Variables:"
              echo "Variable one value: ${ { variables.one } }"
              echo "Variable two value: ${ { variables.two } }"
              echo "Variable one using $(one)"
              echo "Variable two using $(two)"
            displayName: Test Variables
